# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: Sage.Sage50
PackageVersion: 31.20.0.0001
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
